### ISSUE TITLE
setup.py file for client packaging

### ISSUE THREAD

**Issue by avanov** [asyncee/swagger_codegen#3]
Hi! I like your project, and I think it would be good to add a simple packaging boilerplate to a generated client lib so that common packaging operations (`python setup.py sdist bdist_wheel`) can work out of the box. What would be the quickiest way to extend the library renderer for that purpose?

**Comment by asyncee** [comment]
Hi, Maxim!

Glad to hear you like the project!

There are two ways:

1. Subclass [PackageRenderer](https://github.com/asyncee/swagger_codegen/blob/master/src/swagger_codegen/render/package_renderer.py) as DistributablePackageRenderer for example and specify it in .swagger-codegen.toml using `renderer` directive. This way you can keep the code local to your installation without a PR. You should be noted that there are no automated tests for renderers or command line tools that utilise them yet.
2. Implement this feature directly in `PackageRenderer` and making a PR. 

Anyway there are following steps to be done:

1. Template for `setup.py` file should be created [here](https://github.com/asyncee/swagger_codegen/tree/master/src/swagger_codegen/templates/package_renderer). This is usual jinja2 template.
2. `PackageRenderer` class should be extended, see [render method](https://github.com/asyncee/swagger_codegen/blob/master/src/swagger_codegen/render/package_renderer.py#L46)

Please keep in mind that code is not yet optimized and mostly dirtly, because this project was born as a holiday prototype but occasionally it is working okay.

Sadly, i have not much time right now to implement all missing parts, like tests, code optimizations or fully extendable architecture (something like plugin based).
